substitutions:
  name: ext
  friendly_name: "Ext"

packages:
  - !include common/relay-module-switch.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_dacha_ssid
      password: !secret wifi_dacha_password

captive_portal:

web_server:
  port: 80
  local: True

time:
  - platform: sntp
    timezone: UTC-07
    id: sntp_time

one_wire:
  - platform: gpio
    pin: GPIO1

sensor:
  - platform: dallas_temp
    name: temperature_1
    update_interval: 60s

text_sensor:
  - platform: template
    name: "Current time"
    update_interval: 10s
    id: time_text
    lambda: |-
      char str[17];
      time_t currTime = id(sntp_time).now().timestamp;
      strftime(str, sizeof(str), "%c", localtime(&currTime));
      id(time_text).publish_state(str);
      return {str};

