esphome:
  name: relay-module-switch

esp8266:
  board: esp01_1m

logger:

api:
  reboot_timeout: 0s

ota:
  platform: esphome

web_server:
  port: 80

switch:
  - platform: gpio
    name: relay_module_switch_relay
    pin:
      number: GPIO2
      inverted: yes
    id: relay_module_switch_relay
    restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
    name: relay_module_switch_switch
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_state:
      then:
        - switch.toggle: relay_module_switch_relay

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  - platform: uptime
    name: Uptime Sensor